### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by adamltyson** [brainglobe/brainglobe-utils#34]
```[tasklist]
### Tasks
- [x] Add a front-facing user API docs page under `docs/source/documentation/brainglobe-utils` for the `image_io` submodule.
- [x] Add a link to this page in the `docs/source/documentation/index.md` toctree.
- [ ] Add developer documentation (if any), under `docs/source/community/developers/repository`
- [x] Check that all references to `imio` on the brainglobe website are now `image_io` with a link to the new page
```
